<div class="section-widget-container">

    <div class="brator-parts-search-box-area rollparts-design ">
        <form method="get" id="advanced-searchform" class="brator-parts-search-box-form" role="search" action="https://brator-main.smartdemowp.com/shop/">
            <input type="hidden" name="search" value="advanced">
            <select class="select-year-parts brator-select-active select2-hidden-accessible" id="makeyear" name="makeyear" tabindex="-1" aria-hidden="true">
                <option value="">Year</option>
                <option value="2000">2000</option><option value="2001">2001</option><option value="2002">2002</option><option value="2003">2003</option><option value="2004">2004</option><option value="2005">2005</option>					</select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 197.703px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-makeyear-container"><span class="select2-selection__rendered" id="select2-makeyear-container" title="Year">Year</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
            <select class="select-make-parts brator-select-active select2-hidden-accessible" id="makebrand" name="brand" disabled="" tabindex="-1" aria-hidden="true">
                <option value="">Brand</option>
                <option value="bosch">Bosch</option><option value="brigdestone">Brigdestone</option><option value="castrol">Castrol</option><option value="dorman">Dorman</option><option value="michelin">Michelin</option><option value="varta">Varta</option><option value="wruth">Wruth</option>						</select><span class="select2 select2-container select2-container--default select2-container--disabled" dir="ltr" style="width: 202.375px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-labelledby="select2-makebrand-container"><span class="select2-selection__rendered" id="select2-makebrand-container" title="Brand">Brand</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
            <select class="select-model-parts brator-select-active select2-hidden-accessible" id="makemodel" name="model" disabled="" tabindex="-1" aria-hidden="true">
                <option value="">Model</option>
                <option value="a4-prestige">A4 Prestige</option><option value="a6-quattro-premium">A6 Quattro Premium</option><option value="cherokee">Cherokee</option><option value="city-express">City Express</option><option value="civic">Civic</option><option value="colorado">Colorado</option><option value="convertible">Convertible</option><option value="q7-premium">Q7 Premium</option>						</select><span class="select2 select2-container select2-container--default select2-container--disabled select2-container--focus" dir="ltr" style="width: 207.016px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-labelledby="select2-makemodel-container"><span class="select2-selection__rendered" id="select2-makemodel-container" title="Model">Model</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
            <select class="select-engine-parts brator-select-active select2-hidden-accessible" id="makeengine" name="engine" disabled="" tabindex="-1" aria-hidden="true">
                <option value="">Engine</option>
                <option value="camshaft">Camshaft</option><option value="crankshaft">Crankshaft</option><option value="gigabite">gigabite</option><option value="msi">Msi</option><option value="valves">Valves</option>						</select><span class="select2 select2-container select2-container--default select2-container--disabled" dir="ltr" style="width: 211.609px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-labelledby="select2-makeengine-container"><span class="select2-selection__rendered" id="select2-makeengine-container" title="Engine">Engine</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
            <select class="select-fueltype-parts brator-select-active select2-hidden-accessible" id="makefueltype" name="fueltype" disabled="" tabindex="-1" aria-hidden="true">
                <option value="">Fuel Type</option>
                <option value="diesel">Diesel</option><option value="octen">Octen</option><option value="petrol">Petrol</option>						</select><span class="select2 select2-container select2-container--default select2-container--disabled" dir="ltr" style="width: 216.172px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="-1" aria-labelledby="select2-makefueltype-container"><span class="select2-selection__rendered" id="select2-makefueltype-container" title="Fuel Type">Fuel Type</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
            <button type="submit">Search</button>
        </form>
    </div>
</div>
